####
# Author: @apoursh
# Adapted by: @zafarali
# This script takes in a vcf generated by msprime
# and prepares it for this pipeline
# (1) assigns rsids to each snp according to chromosome and position number
# (2) creates 3 files with information about individuals in each population.
####

popFolder="PopInds"

zcat $1 | awk '{if ($3==".") $3=$1":"$2; print$0}' | gzip -c > ${1}_with_rsids.gz
zcat ${1}_with_rsids.gz | head -20 | grep '#CHROM' | cut -f10- | sed 's/\t/\n/g' > temp.names
lines=`cat temp.names | wc -l`
echo "number of individuals is:"
echo $lines
s=$(( lines / 3 ))
split -l$s temp.names
mkdir $popFolder
rm temp.names
mv xaa $popFolder/YRI
mv xab $popFolder/CEU
mv xac $popFolder/CHB
